sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
- sudo apt-get install ant-optional
addons:
  hosts:
    - myshorthost
  hostname: myshorthost

script:
- ant -buildfile ./framework/build.xml test

after_failure:
    find samples-and-tests -name '*.failed.html' -exec echo {} \; -exec cat {} \;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6da3b55e59cded84b8bd
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: always
