package MyApplicationPermissions;

import play.modules.securePermissions.PermissionCheck;
import play.modules.securePermissions.Role;

import models.Item;

/* Super user can do everything */
rule IsSuperUser
when
  $c: PermissionCheck(action in ("delete", "update", "insert"))
  Role(name == "super-user")
then
  $c.grant();
end

/* Normal user can only edit postcards */
rule CanUserEditPostcard
when
  $cs: Item(name == "postcard")
  $c: PermissionCheck(target == $cs, action in ("delete", "update", "insert"))
then
  $c.grant();
end

/* Admins can only edit postcards and letters */
rule CanUserEditLetter
when
  $cs: Item(name == "letter")
  $c: PermissionCheck(target == $cs, action in ("delete", "update", "insert"))
  Role(name == "admin")
then
  $c.grant();
end

