function main(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',vb='3B0C581197DADA1111B2D57760D0BC22.cache.html',tb='906F81BFEDA0AF63B6A8F359AF44224C.cache.html',sb='9EBBA50E1D4E76D448B16249B88B5171.cache.html',Fb='<script defer="defer">main.onInjectionDone(\'main\')<\/script>',dc='<script id="',A='=',q='?',wb='AAA451E1A0B33BDBA7D9B03E6F8401F9.cache.html',C='Bad handler "',ub='CAF382275039C3B30CB95B9FF85CDE11.cache.html',Eb='DOMContentLoaded',o='SCRIPT',cc='__gwt_marker_main',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',bc='end',lb='gecko',mb='gecko1_8',yb='gwt.hybrid',xb='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',Db='head',qb='hosted.html?main',Cb='href',kb='ie6',ab='iframe',t='img',bb="javascript:''",zb='link',pb='loadExternalRefs',m='main',v='meta',eb='moduleRequested',ac='moduleStartup',jb='msie',w='name',gb='opera',db='position:absolute;width:0;height:0;border:none',Ab='rel',ib='safari',rb='selectingPermutation',x='startup',Bb='stylesheet',ob='unknown',fb='user.agent',hb='webkit';var fc=window,k=document,ec=fc.__gwtStatsEvent?function(a){return fc.__gwtStatsEvent(a)}:null,zc,pc,kc,jc=l,sc={},Cc=[],yc=[],ic=[],vc,xc;ec&&ec({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!fc.__gwt_stylesLoaded){fc.__gwt_stylesLoaded={}}if(!fc.__gwt_scriptsLoaded){fc.__gwt_scriptsLoaded={}}function oc(){var b=false;try{b=fc.external&&(fc.external.gwtOnLoad&&fc.location.search.indexOf(yb)==-1)}catch(a){}oc=function(){return b};return b}
function rc(){if(zc&&pc){var c=k.getElementById(m);var b=c.contentWindow;if(oc()){b.__gwt_getProperty=function(a){return lc(a)}}main=null;b.gwtOnLoad(vc,m,jc);ec&&ec({moduleName:m,subSystem:x,evtGroup:ac,millis:(new Date()).getTime(),type:bc})}}
function mc(){var j,h=cc,i;k.write(dc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){jc=f(j.src)}if(jc==l){var e=k.getElementsByTagName(s);if(e.length>0){jc=e[e.length-1].href}else{jc=f(k.location.href)}}else if(jc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=jc+u;jc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function wc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}sc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{xc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{vc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function Bc(d,e){var a=ic;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function lc(d){var e=yc[d](),b=Cc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(xc){xc(d,a,e)}throw null}
var nc;function qc(){if(!nc){nc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);ec&&ec({moduleName:m,subSystem:x,evtGroup:ac,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(jc+Ac)}}
yc[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return kb}}}else if(d.indexOf(lb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return mb}return lb}return ob};Cc[fb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};main.onScriptLoad=function(){if(nc){pc=true;rc()}};main.onInjectionDone=function(){zc=true;ec&&ec({moduleName:m,subSystem:x,evtGroup:pb,millis:(new Date()).getTime(),type:bc});rc()};mc();var Ac;if(oc()){if(fc.external.initModule&&fc.external.initModule(m)){fc.location.reload();return}Ac=qb}wc();ec&&ec({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:rb});if(!Ac){try{Bc([kb],sb);Bc([gb],tb);Bc([ib],ub);Bc([mb],vb);Bc([lb],wb);Ac=ic[lc(fb)]}catch(a){return}}var uc;function tc(){if(!kc){kc=true;if(!__gwt_stylesLoaded[xb]){var a=k.createElement(zb);__gwt_stylesLoaded[xb]=a;a.setAttribute(Ab,Bb);a.setAttribute(Cb,jc+xb);k.getElementsByTagName(Db)[0].appendChild(a)}rc();if(k.removeEventListener){k.removeEventListener(Eb,tc,false)}if(uc){clearInterval(uc)}}}
if(k.addEventListener){k.addEventListener(Eb,function(){qc();tc()},false)}var uc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){qc();tc()}},50);ec&&ec({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:bc});ec&&ec({moduleName:m,subSystem:x,evtGroup:pb,millis:(new Date()).getTime(),type:nb});k.write(Fb)}
main();