name: Release Drafter

on:
  push:
    branches:
      - master

permissions: {}
jobs:
  update_release_draft:
    permissions:
      pull-requests: write # to add label to PR (release-drafter/release-drafter)
      contents: write # to create a github release (release-drafter/release-drafter)

    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          name: "Play $RESOLVED_VERSION"
          config-name: release-drafts/increasing-minor-version.yml # located in .github/ in the default branch within this or the .github repo
          commitish: ${{ env.GITHUB_REF_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
